### ISSUE TITLE
Reduce minimal Nim version ? 

### ISSUE THREAD

**Issue by Clonkk** [treeform/print#10]
Print fails to install because it requires Nim >= 1.4.6. 

Is it a fixed requirement or would it be possible to lower the minimum Nim version ?

**Comment by treeform** [comment]
I don't know. Can you test with which version you have and I can set it to that?

**Comment by Clonkk** [comment]
I've tested down to Nim v1.4.0 and print seems to work.

I've since upgraded to v1.4.8 so not really relevant anymore
