### ISSUE TITLE
error: incompatible type when dumping some importc structs

### ISSUE THREAD

**Issue by arkanoid87** [treeform/print#17]
I'm dealing with a quite large c2nim wrapped lib. It works nicely with echo/dump but print is much better as it walks automatically through the ptr Object(s).

But sometimes it fails when some types are encountered.

```
/home/jack/snap/codium/common/.cache/nim/test_onvif_d/@m..@s..@s..@s.nimble@spkgs@sprint-@hhead@sprint.nim.c:2390:46: error: incompatible type for argument 1 of ‘newNode__6poDW5ZzQqbrmF9aP9cTv2cg’
 2390 |  T14_ = newNode__6poDW5ZzQqbrmF9aP9cTv2cg(x_0.UtcTime); <--  time_t {aka long int}
```

**Comment by treeform** [comment]
Could you provide a bigger snippet? with the library you used. I tested all of the nim's c compatibility types and they all work.

**Comment by treeform** [comment]
Sorry I am going to close this. If you can provide a minimum sample I might be able to fix it. But without this I don't know what the error is.
