### ISSUE TITLE
Not thread-safe

### ISSUE THREAD

**Issue by ajusa** [treeform/print#26]
Tried using this in a mummy handler and the handler became non-gcsafe. My guess is that the global variables in https://github.com/treeform/print/blob/master/src/print.nim#L23-L26 are causing an issue, but I haven't looked further into it.

While it's true that printing to the terminal should be locked by a lock to prevent races, I think that this library is more for debugging so maybe a cast(gcsafe) could be enough if safety isn't the first priority.

**Comment by treeform** [comment]
Have you tried using https://github.com/treeform/pretty instead?

**Comment by ajusa** [comment]
That does work perfectly! I developed muscle memory around `import print` at some point, didn't realize that you rewrote it and made it work.
