### ISSUE TITLE
print type with `$` defined should use it 

### ISSUE THREAD

**Issue by Clonkk** [treeform/print#8]
Type that uses their own `$` proc should be printed using it. 

This is useful for type that depends on UncheckedArray and have defined their own `$` : calling ``print`` will not compile while ``echo`` will work.

A simple example of this is with Arraymancer (you can find the `$`implementation [here](https://github.com/mratsim/Arraymancer/blob/master/src/arraymancer/tensor/display.nim) )

```Nim

import print
import arraymancer

var a = @[1, 2, 3].toTensor
print a
```

Output  (truncated a bit) : 
```
template/generic instantiation of `print` from here
/home/rcaillaud/.nimble/pkgs/print-0.2.0/print.nim(212, 23) template/generic instantiation of `prettyPrint` from here
/home/rcaillaud/.nimble/pkgs/print-0.2.0/print.nim(134, 24) template/generic instantiation of `prettyPrint` from here
/home/rcaillaud/.nimble/pkgs/print-0.2.0/print.nim(179, 25) template/generic instantiation of `prettyPrint` from here
/home/rcaillaud/.nimble/pkgs/print-0.2.0/print.nim(134, 24) template/generic instantiation of `prettyPrint` from here
/home/rcaillaud/.nimble/pkgs/print-0.2.0/print.nim(198, 27) Error: type mismatch: got <UncheckedArray[int]>
```

**Comment by treeform** [comment]
I don't think I want to use `$` for stuff. I have run into too many cases were the `$` just hidden info i need to debug the problem. I would rather print the structure of the thing.

I feel like the problem here is that i don't support UncheckedArray, which I should.

**Comment by treeform** [comment]
I added support for unchecked array: https://github.com/treeform/print/commit/8b185fd6c6fcf84c5a79a7305ce942cfce9ba913

See if that works for you?

**Comment by Clonkk** [comment]
![Capture](https://user-images.githubusercontent.com/35006197/107567829-813f6e00-6be6-11eb-8b2e-da23dd466e44.PNG)

Looks good to me !
